#! /bin/bash
if [ $USER != "millenium" ] ; then
        echo "This script must be run by millenium"
        exit 1
else
screen -S empad_python_IOC -X kill 
cd /home/millenium/ioc/scripts/
sleep 2
screen -S empad_python_IOC ./run_python_ioc.sh
fi
